### ISSUE TITLE
Añadir autores y fecha de creación de cada solución

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#16]
Añadir los autores de cada solución como una cabecera en cada archivo que forme parte de la solución del problema. Así queda claro quien es el autor y por tanto se ve a quien hay que hacerle las preguntas si algo falla.

La cabecera en los archivos `.c` seria como la que ya pone el Clion por defecto:
```
//
// Created by {AUTHOR} on 28/1/22.
//
```

En los archvios `.s` seria:

```
@; Created by  {AUTHOR} on 28/1/22.
```

Donde `{AUTHOR}` es el nombre completo del autor, tal y como aparece en los Acknowledgements del `README.md` principal

**Comment by AleixMT** [comment]
Añadir esta explicación en el `README.md` o donde sea necesario.

**Comment by AreyFerreroRamos** [comment]
En mi opinión, el lugar en el que debe ser imprescindible añadir el nombre del autor del problema y la fecha en que lo realizó es en el README.md. En los ficheros .c i .s no creo que sea necesario. No obstante, si lo quieres añadir, adelante.

**Comment by AleixMT** [comment]
Te refieres al [`README.md` general del repositorio](https://github.com/AleixMT/Problemas-Computadores/blob/master/README.md) o te refieres a los `README.md` que tienen cada carpeta de problema? 

La idea en #17 es que usaremos los `README.md` de cada problema para hacer el display del enunciado. Los datos correspondientes que hasta ahora iban en el `README.md` los pasaría a un archivo rollo `EXPLICACIONES.md` o algo así, y ahí también iría el nombre del autor de la solución. 

Quiero firmar con el nombre del autor individualmente cada archivo de código porque como bien dices hay códigos (sobre todo `main`s) que no los hemos hecho nosotros i no aparecen firmados por el autor original.

**Comment by AreyFerreroRamos** [comment]
Me refiero a los README.md que tiene cada problema o, en caso de que utilices dichos README.md para albergar el enunciado del problema, al archivo EXPLICACIONES.md (que yo llamaría, si acaso, EXPLICACIÓN.md).

El motivo por el que yo no pondría el nombre del autor en las cabeceras de los ficheros '.c' y '.s' es porque esto puede resultar confuso para los alumnos ya que igual piensan que ellos también lo tienen que poner.

**Comment by AleixMT** [comment]
¿Y por qué no deberían firmar las soluciones con su nombre si son de su autoría?

**Comment by AleixMT** [comment]
De momento lo he llamado `SOLUTION.md` porque las tildes en los nombres de los archivos le sientan bastante mal a git.
