### ISSUE TITLE
Añadir display del enunciado en cada uno de los `README.md` de cada problema

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#17]
Mostrar el enunciado en el `README.md` de cada problema. Para hacer el display, hay que convertir cada PDF de enunciado a PNG , subirlo al repo y usar la dirección raw de github hacia ese recurso para que el `README.md` pueda insertar el PDF como una imagen.

Eso nos deja con la incógnita de qué hacer con el contenido actual del `README.md`. Yo lo movería a otro archivo `.md` en la carpeta de cada problema. Este archivo podria llamarse `RAZONAMIENTO.md` o `EXPLICACIONES.md` y básicamente ahí meteríamos todos los conceptos relevantes que se hayan explicado en el problema y también seria donde añadiríamos las respuestas a las preguntas teóricas de haberlas.

Hay que añadir la explicación relevante en el `README.md` o donde sea necesario de estas nuevas reglas.

**Comment by AreyFerreroRamos** [comment]
Yo esto tengo dudas sobre si cambiarlo o no. La razón fundamental es que estos enunciados no nos pertenecen y, por lo tanto, puede que sea mejor tenerlos de modo que sean fáciles de eliminar y que no parezcan hechos por nosotros como si nos hubiésemos querido apropiar del trabajo de otra persona.

**Comment by AleixMT** [comment]
Están en un repositorio público de Git. No hay forma "fácil" de borrarlos (¿Has oído hablar de `git rebase` o `git cherry-pick`?) a parte de borrar el repositorio o hacerlo privado.

No pienso que parezca que nos hemos apropiado del trabajo de otra persona, el nombre del autor está en los agradecimientos y debido al issue #16 el nombre aparecerá en todos los códigos que vengan dados por el enunciado. 

¿Qué es lo que crees que hace que parezca que los enunciados han sido hechos por nosotros? ¿Cómo crees que se podría mejorar? 

De todas formas, la PR está en camino. Indiferentemente, si surgiese cualquier cosa, sería el mismo esfuerzo borrar los `.pdf` que borrar los `.png` que serán añadidos por la PR que resuleve este issue.

**Comment by AreyFerreroRamos** [comment]
Dado que no se exactamente como funciona el copyright, no puedo responder a muchas de las preguntas que se me proponen. Sencillamente planteo la posibilidad de que pueda existir algún riesgo. No obstante, si afirmas que no lo hay, confiaré en ti. Así que tus propuestas me parecen bien.

**Comment by AleixMT** [comment]
Yo no he dicho que no haya ningún riesgo, tampoco soy un experto en patentación y protección intelectual. Lo que sé es que de momento los `.pdf`s estan subidos y no hemos tenido ningún problema, así que considero que subir los `.png`s no nos llevará a un escenario peor. Es decir, en todo caso ya nos hemos pateado el contenido protegido por copyright así que añadir imágenes de ese mismo contenido no implicará ninguna diferencia en este tema. 

Si crees que es algo a tratar abre un issue a parte para este tema y lo discutimos entre los tres, pero en principio el daño ya está hecho.

**Comment by AleixMT** [comment]
"daño"

**Comment by AreyFerreroRamos** [comment]
De acuerdo. Me parece bien. Convierte los enunciado en 'png'.
