### ISSUE TITLE
Meter carpetas de problemas en su propia carpeta "Problemas" en la raíz del repo

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#18]
Cuando entras al repo al haber tantas carpetas no se ve bien el `README.md` y tienes que bajar muy a bajo para verlo. Propongo poner las carpetas en una carpeta general para las soluciones, así el número de elementos en la raíz del repo disminuye y queda más "limpio"

**Comment by AreyFerreroRamos** [comment]
Me parece una muy buena idea. Como dices, esto facilitará el acceso al README.md.
