### ISSUE TITLE
Reorganizar y añadir nuevas columnas a la tabla del `README.md`

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#19]
Primero de todo me gustaría mover o borrar la leyenda de los corazoncitos porque me parece poco profesional. Está bien si lo dejamos como referencia virual pero creo que el nivel de calidad de la solución tiene que verse escrito en la columna.

Luego me gustaría refinar los emojis del ojo y del simbolo de descarga. Me gustaria que la segunda columna se llamara "Enunciado" y tuviera un emoji para ver el enunciado y otro para descargarlo. Ver el enunciado te llevaría al display de GitHub del `.pdf` y descargar el enunciado te llevaría a la descarga raw del enunciado.

Luego, en la columna de la solución, poner un emoji para ver la solución, lo cual te llevara a la carpeta del problema, donde el `README.md` displayea el enunciado. 

Luego podríamos añadir 4 columnas: Programa principal, RSIs, Funciones en assembler, Explicaciones. Cada una de ellas tiene uno o más links a cada uno de los elementos correspondientes de la solucion. De esta forma la tabla principal del `README.md` se convierte en una tabla de contenidos con una forma muy conveniente de navegar por las solucionesd el repositorio. 

¿Que os parece?

**Comment by AreyFerreroRamos** [comment]
En general me parece bien. Es cierto que hay alguna cosa que no termino de entender a que te refieres, pero en este caso, me parece interesante que lo pruebes y, si no nos gusta como queda, se cambia sin problemas.

**Comment by AleixMT** [comment]
Me refiero a la tabla del [`README.md`](https://github.com/AleixMT/Problemas-Computadores/blob/master/README.md). Échale un ojo si no lo has leído.

**Comment by AreyFerreroRamos** [comment]
Le he echado un ojo y me parece bien. A parte de eso, estaba pensando que a mi sique me gustan los corazones y, dado que es un repositorio pensado para ser consultado por estudiantes universitarios de segundo año de carrera, no me parece que quede poco profesional. No obstante, si lo cambias, supongo que la opción alternativa que propongas será mejor, así que adelante.

**Comment by AleixMT** [comment]
Básicamente me molesta que haya una leyenda para explicar el significado de los corazones en relación a las soluciones. Prefiero dejarlo claro para no tener que añadir ninguna explicación extra (lo bueno, si breve, dos veces bueno). 

A mi el tema de los corazones tampoco me parece mal. Pero se puede simplificar. Aunque tampoco tengo decidida una propuesta aún ¿Tienes alguna idea?

**Comment by AreyFerreroRamos** [comment]
La verdad es que no tengo ninguna idea. Lo de los corazones me parecía bien porque el color recordaba a semáforos, aunque si lo que persigues es la brevedad, siempre está bien. Si tengo alguna idea abriré un nuevo 'issue'.
