### ISSUE TITLE
Duda Problema 12

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#20]
Lo que te comento está en el RSI, sí. Pero no me refería a eso. Te explico:

El programa empieza con `fase = 0`. Se inicia el pulso (interrupción). Entramos en la rutina del RSI donde seguimos con `fase = 0`. Si miras el código de la RSI verás que si la `fase = 0` pasa directamente al `bl cpuGetTiming` (que te da los tics que ha calculado el cronómetro) sin antes haber pasado antes por `bl cpuStartTiming` (que inicia el cronómetro). Por lo tanto, considero que no va a recoger ningún tic porque el cronómetro no se ha iniciado en ningún momento.

![image](https://user-images.githubusercontent.com/23342150/205911787-35b1a6fa-864d-4281-9b05-d0de86bae803.png)

@AreyFerreroRamos  Este problema lo hiciste tú, puedes revisarlo?

**Comment by AreyFerreroRamos** [comment]
La observación es correcta. En la línea 7 de la RSI, la instrucción debería ser 'bne .Lcapturar_tiempo'

**Comment by AleixMT** [comment]
@AreyFerreroRamos Puedes levantar una PR y corregirlo?

**Comment by AreyFerreroRamos** [comment]
El issue se ha resuelto con éxito
