### ISSUE TITLE
Errores en la solución oficial del problema 5

### ISSUE THREAD

**Issue by AreyFerreroRamos** [AleixMT/Problemas-Computadores#29]
He hallado dos errores en la solución oficial del problema 5.
En la línea 27 del fichero 'RSI_timer0.s' se utiliza la instrucción 'mul r4, r3, #6'. Esta instrucción es incorrecta dado que no se puede utilizar un operando inmediato como segundo operando fuente en la instrucción de multiplicación del ARM (Explicado en el último párrafo de la página 32 del documento 'Teoría de lenguaje máquina y ensamblador de procesadores ARM'). Una forma correcta de implementarlo sería usando primero la instrucción 'mov r4, #6' seguida de la instrucción 'mul r4, r3, r4'.
En la línea 26 del fichero 'activar_nota.s' se utiliza la instrucción 'orr r2, #0xA0000000'. A pesar de que esta instrucción no es incorrecta en cuanto a sintaxis del lenguaje ARM, si lo es con respecto a la información proporcionada en el enunciado del problema. En dicho enunciado se especifica que los bits del registro SOUND_X_CNT que permiten especificar el modo de repetición son los bits 28 y 27. En concreto, para el modo de repetición en bucle infinito, el bit 28 tendrá que estar a 0 y el bit 27 a 1, lo que hace que la máscara utilizada sea incorrecta. La instrucción correcta deberá ser 'orr r2, #0x88000000'.

**Comment by AleixMT** [comment]
El primer cambio es correcto. 👍 

El segundo también 👍 , pero ten en cuenta que ese cambio ya se documentó en el issue #9 que cerraste sin resolver. Los issues se cierran cuando estan resueltos, sino terminas documentando los issues por dos (como acaba de pasar). 

![image](https://user-images.githubusercontent.com/23342150/208296046-91c249f2-fe00-4fca-962f-312a9f61b25b.png)

Lo he reabierto. Cierralo cuando tengas la PR que implementa estos dos cambios cerrada 💯

**Comment by AreyFerreroRamos** [comment]
De acuerdo. Voy con ello.

**Comment by AleixMT** [comment]
Ahora es cuando se debe cerrar el issue 👍

**Comment by AreyFerreroRamos** [comment]
Cierro el issue.
