### ISSUE TITLE
Fix request: El link del problema 39 para ver y descargar erróneamente apunta al 37

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#41]
Ambos links del problema 39 en la tabla del `README.md` principal apuntan erróneamente al problema 37. Deben apuntar al problema 39.

Seguramente se debió hacer mal cuando añadí los problemas.

Gracias [@IsaacChortó](https://github.com/IsaacChorto)

**Comment by AreyFerreroRamos** [comment]
Perfecto. No hacía falta pedir permiso para solucionar este problema, :)

**Comment by AleixMT** [comment]
Por lo general, un *issue* es una forma estándar de documentar, discutir y requerir cambios o indicar problemas en la especificación de un programa que luego puede llegar a derivar a una *pull request* que haga la implementación necesaria para resolver el issue.

En este case lo hago por (en orden de importancia):
- Requerimiento: De un alumno.
- Documentación: Del problema detectado.
- Completitud y buenas prácticas: **Si es un cambio o problema en spec, entonces debe ser un *issue* **.
- Aprendizaje: Hasta donde yo sé, ésta es la forma estándar de trabajar en un repo "serio" (sea una empresa o un software opensource) y quiero familiarizarme con ella.

Así que en principio no esperaba un permiso ni una discusión del cambio porque es bastante directo, pero me vale la pena escribir el *issue*.

**Comment by AreyFerreroRamos** [comment]
Comprendo. Es una muy buen forma de practicar, sí. Yo haré lo mismo.

**Comment by AleixMT** [comment]
@AreyFerreroRamos No cierres issue, todavía no se ha resuelto porque no se ha implementado nada.

**Comment by AreyFerreroRamos** [comment]
De acuerdo. Pensaba que cuando se llegaba a un acuerdo, el issue se podía cerrar. A partir de ahora no los cerraré.

**Comment by AleixMT** [comment]
Ahora sí que se puede cerrar 👯‍♂️
