### ISSUE TITLE
Añadir disclaimer legal

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#44]
Añadir un archivo `LICENSE.md` o `LICENSING.md` o `DISCLAIMER.md` donde se detalle el estado legal y de propiedad intelectual del proyecto.

**Comment by AreyFerreroRamos** [comment]
Me parece correcto.

**Comment by AreyFerreroRamos** [comment]
La PR ya está aprobada, por lo que procedo a cerrar el issue.
