### ISSUE TITLE
Problema 19: Encontrada solución de profesor. Hay que pasarla a limpio y subirla

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#47]
[ExamenC1_mati.pdf](https://github.com/AleixMT/Problemas-Computadores/files/10277078/ExamenC1_mati.pdf)

**Comment by AreyFerreroRamos** [comment]
De acuerdo. Me puedo ocupar yo, si quieres. Pero no podré hacerlo hasta el viernes o el sábado.

**Comment by AleixMT** [comment]
No hay prisa. Lo haré yo si encuentro algún momento.

**Comment by AleixMT** [comment]
Bueno te asigno lo asigno a ti, y si no puedes tampoco pasa nada.

**Comment by AreyFerreroRamos** [comment]
De acuerdo, pues entre hoy mañana intento hacerlo.
