### ISSUE TITLE
Revisión problema 17

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Problemas-Computadores#51]
Falta revisar el código del problema 17 y añadir un poco de estilo, algun comentario , bloques de código, etc.

**Comment by AreyFerreroRamos** [comment]
De acuerdo. ¿Entiendo que no has podido revisar el código entonces, no? Todo lo que dices me parece bien, aunque el estilo y la cantidad de comentarios es la misma que en el resto de problemas que he hecho.

**Comment by AleixMT** [comment]
No, no lo he revisado. Efectivamente, el estilo es inexistente y la cantidad de comentarios es casi 0. Muy mejorable.

**Comment by AreyFerreroRamos** [comment]
Lo de los comentarios puedo estar de acuerdo. Aunque yo no pongo comentarios mientras realizó el problema debido a que intento cuadrarlo en dos horas, es razonable afirmar que en el momento de transcribirlo al repo se pueden añadir. Por otro lado, no estoy de acuerdo con que el estilo sea inexistente. Durante todos los años en los que he realizado los problemas he evolucionado hacia el estilo con el que a mí me resulta más sencillo comprender el código en caso de que deba releerlo (ciertas tabulaciones, todos los comentarios con la misma tabulación, ningún espacio entre líneas,...). Otra cosa bien distinta es que se busque que todos los problemas sigan los mismos criterios estilísticos o que uno o varios profesores consideren que mi estilo no es el más claro para la amplia mayoría de los alumnos. En dichos casos, no tengo ningún problema en hacer cambios sin necesidad de debatirlos. No obstante, si este es el caso, yo no podía saber esto de antemano, dado que sí que aplicaba un criterio estilístico.

**Comment by AleixMT** [comment]
¿Me puedes explicar **objetivamente** como puede ayudarte a comprender mejor el código no poner ningun espacio entre lineas?

Está claramente estudidado que causa el efecto contrario en el ser humano (Gestalt). Es por ello que los textos tienen párrafos. Y para el código, como texto que es, son aplicables las mismas reglas.

¿Entonces la guía de estilo que usas son normas subjetivas y arbitrarias que no están escritas en ningún sitio? 

Yo uso [éstas](https://www.cs.umd.edu/~nelson/classes/resources/cstyleguide/), las cuales dicen algo bastante razonable y universal sobre los comentarios y los bloques de código que literalmente vas a encontrar en todas las guías de estilo de todos los lenguajes de programación:

![image](https://user-images.githubusercontent.com/23342150/215470765-2f8a5852-743d-4d6a-aea3-270fb89e8d2a.png)

PD2: Óbviamente para describir el *intent* de un bloque de código (párrafo) primero hay que tener el código definido en bloques, lo cual necesariamente implica tener que usar espacios entre lineas. 

PD: *markdown* también permite uso de párrafos.

**Comment by AreyFerreroRamos** [comment]
Efectivamente, yo no he seguido ninguna guía de estilo oficial sobre como redactar un código usando el lenguaje máquina de los procesadores ARM y el lenguaje ensamblador GAS. Así, me gustaría destacar, que no estoy tratando de convencerte de que la forma en la que he redactado el código de los problemas hasta ahora sea mejor y más comprensible para la amplia mayoría de las personas. Yo también conozco estudios que afirman que los párrafos facilitan la lectura y, de hecho, fue por ello, que hace unos años reescribí buena parte de mis relatos para adaptarlos ha dicho estilo (estilo que hasta entonces no seguía). Por ello, no tengo ningún problema en transitar al estilo oficial que tú pretendes que sigamos.

Aclarado este punto, sí que también debo destacar que mi estilo aunque subjetivo, en ningún caso es arbitrario o consecuencia de una falta de interés en hacer las cosas de manera correcta. Sino que es un estilo al que he ido transitando a medida que he ido haciendo más y más problemas en ARM porque me ha proporcionado una serie de ventajas.

Para empezar, al no separar el código en párrafos ni introducir comentarios con la misma tabulación que las líneas de código, dicho código queda más compacto. Esto permite hacerte una idea instantánea de la verdadera longitud del código. De modo que, si haces un problema por segunda vez y te has olvidado de algún apartado, esto resultará en una longitud sustancialmente diferente que se puede apreciar sin leer el código en profundidad y puedes revisar el problema que acabas de hacer en busca del error sin que hayas descubierto todavía de que error se trata. Dado que el añadido de líneas en blanco es (relativamente) arbitrario la longitud de ambos códigos puede ser muy diferente y se pierda esta ventaja. Además, un código que ocupa una única página (algo más probable, cuanto más compacto sea) me resulta más fácil de leer.

Segundo, hasta ahora no he añadido comentarios porque debido a mis conocimientos de ARM, el código me resulta explicativo por sí mismo. Si a esto le sumas que muchas de las líneas de comentario no siguen una tabulación estricta y que, además, en muchas ocasiones se limitan a mostrar la instrucción equivalente en c sí, me atrevo a afirmar sin ningún tipo de duda que, en ocasiones los comentarios lejos de facilitarme la comprensión del código hacen que este me parezca que está recargado y me cueste más leerlo.

Por último, me gustaría destacar que los registros que elijo para cargar variables, contenidos de estas, direcciones base de vectores o tablas, y sus índices no es arbitrario, sino que trata de ser coherente (aunque no siempre me resulta posible) con los problemas que se han realizado anteriormente, algo que no sólo es un criterio de estilo definido (que no necesariamente correcto, pero si existente y que lleva cierto trabajo), sino que también es algo que hacía el Dr. Santiago Romaní cuando resolvía problemas.

Quiero destacar de nuevo, que no estoy tratando de convencerte de que mi estilo se bueno, eficiente o facilite la comprensión a la amplia mayoría de personas. Insisto en que no tengo ningún problema en transitar hacia un estilo oficial. Sencillamente me he limitado a responder a tus preguntas.

**Comment by AleixMT** [comment]
De acuerdo, lo entiendo. Yo lo único que digo es que está muy bien que no quieras poner ningún comentario o ninguna linea en blanco en tus códigos si a ti particularmente te resulta más cómodo, pero no estamos intentando **optimizar tu comodidad**, sinó que intentamos **optimizar el tiempo de comprensión de los alumnos** y este estilo es contraproducente para esta métrica. Que sí, que yo puedo dedicarme a poner comentarios y luego a segmentar tu código en bloques, pero eso es algo que yo creo que deberías hacer tú mismo, más que nada porque el autor del código ya sabe lo que hace el código y por tanto le resulta mucho menos costoso.

Contestando al resto de cuestiones:

- Sí, el añadido de lineas en blanco es bastante arbitrario y subjetivo. Tan arbitrario y subjetivo como lo puede ser la separación en párrafos: Quizá no sea un concepto formalmente definible, pero las personas sabemos discernir donde "iria bien" un punto y a parte. 
- Lo de que te quepa en la pantalla es algo subjetivo para la pantalla que usas. En mi pantalla 4K con la letra normal no hay problema que no me quepa entero en la pantalla, no importa que se hayan dejado varias lineas en blanco. Alternativamente, en el movil nunca soy capaz de ver el problema entero, no importa lo muy compacto que esté.
- Para contar las lineas de código de un archivo fuente te recomiendo no confiar en la vista, sinó en una buena herramienta que haga precisamente esta tarea: Por ejemplo puedes usar la utilidad de terminal [`cloc`](https://cloc.sourceforge.net/).
- Que las lineas de comentarios no sigan una tabulación estricta es directamente culpa de quien haya tabulado incorrectamente los comentarios. También tiene que ver con *indentar* usando tabuladores, desconociendo que los tabuladores NUNCA deben usarse para esto puesto que el número de espacios que ocupa un tabulador en pantalla no es fijo.
- No entiendo el comentario de la coherencia en el uso de variables.

**Comment by AleixMT** [comment]
Y sobre el tema del estilo pues tengo que redactarlo para que haya unas normas de estilo claras y definidas de la forma más formal posible. Luego ya discutiremos los detalles, pero las cosas *basics* como no poner absolutamente ningún comentario en el código o código sin ninguna separación entre líneas las doy por superadas.
