### ISSUE TITLE
Función activar_nota()

### ISSUE THREAD

**Issue by sergioarevro** [AleixMT/Problemas-Computadores#9]
**En la función activar_nota linea 22:** ¿No debería ser 0x88 para activar el start y el bucle infinito?. Es decir:

Inicio más bucle infinito

B31 1
B30 X
B29 X
B28 0
B27 1

0x8800 0000

**Comment by AleixMT** [comment]
Problema 5

**Comment by AleixMT** [comment]
Perfecto @AreyFerreroRamos, esperamos una PR arreglándolo en caso que concluyas que está mal la versión actual 💪

**Comment by AreyFerreroRamos** [comment]
Perfecto entonces.

**Comment by AreyFerreroRamos** [comment]
Supongo que esto lo tengo que solucionar modificando el código y siguiendo el procedimiento usual para hacer una pull request, no?

**Comment by AleixMT** [comment]
Se supone que esto ya lo has corregido en la PR #36, cierro issue. (El problema es que se cerró este issue sin completarse y han terminado habiendo dos issues documentando el mismo error)

**Comment by AleixMT** [comment]
Bueno, lo reabro hastas que lo tengamos mergeado, pensava que ya estaba. Lo mismo para #29

**Comment by AreyFerreroRamos** [comment]
Ahora el problema ya está solucionado.  Cierro el issue.
